/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ArisanGroupFactoryInterface extends utils.Interface {
  functions: {
    "createGroup(string,string,string,uint256,uint256,uint256)": FunctionFragment;
    "getGroupAddreseses()": FunctionFragment;
    "groupAddreseses(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createGroup"
      | "getGroupAddreseses"
      | "groupAddreseses"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGroup",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupAddreseses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "groupAddreseses",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupAddreseses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "groupAddreseses",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ArisanGroupFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArisanGroupFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createGroup(
      title: PromiseOrValue<string>,
      telegramGroupUrl: PromiseOrValue<string>,
      coordinatorTelegramUsername: PromiseOrValue<string>,
      coordinatorRewardPercentage: PromiseOrValue<BigNumberish>,
      contributionAmountInWei: PromiseOrValue<BigNumberish>,
      prizePercentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getGroupAddreseses(overrides?: CallOverrides): Promise<[string[]]>;

    groupAddreseses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createGroup(
    title: PromiseOrValue<string>,
    telegramGroupUrl: PromiseOrValue<string>,
    coordinatorTelegramUsername: PromiseOrValue<string>,
    coordinatorRewardPercentage: PromiseOrValue<BigNumberish>,
    contributionAmountInWei: PromiseOrValue<BigNumberish>,
    prizePercentage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getGroupAddreseses(overrides?: CallOverrides): Promise<string[]>;

  groupAddreseses(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createGroup(
      title: PromiseOrValue<string>,
      telegramGroupUrl: PromiseOrValue<string>,
      coordinatorTelegramUsername: PromiseOrValue<string>,
      coordinatorRewardPercentage: PromiseOrValue<BigNumberish>,
      contributionAmountInWei: PromiseOrValue<BigNumberish>,
      prizePercentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getGroupAddreseses(overrides?: CallOverrides): Promise<string[]>;

    groupAddreseses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createGroup(
      title: PromiseOrValue<string>,
      telegramGroupUrl: PromiseOrValue<string>,
      coordinatorTelegramUsername: PromiseOrValue<string>,
      coordinatorRewardPercentage: PromiseOrValue<BigNumberish>,
      contributionAmountInWei: PromiseOrValue<BigNumberish>,
      prizePercentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getGroupAddreseses(overrides?: CallOverrides): Promise<BigNumber>;

    groupAddreseses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createGroup(
      title: PromiseOrValue<string>,
      telegramGroupUrl: PromiseOrValue<string>,
      coordinatorTelegramUsername: PromiseOrValue<string>,
      coordinatorRewardPercentage: PromiseOrValue<BigNumberish>,
      contributionAmountInWei: PromiseOrValue<BigNumberish>,
      prizePercentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getGroupAddreseses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    groupAddreseses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
